[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ElectronDisplay = "d872a56f-244b-5cc9-b574-2017b5b909a8"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MPICH_jll = "7cb0a576-ebde-5e09-9194-50597f1243b4"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
ParameterEstimocean = "eca81dc5-87a6-4430-aec8-c76695404a43"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
